USE fitness_records;

CREATE TABLE IF NOT EXISTS activity_plans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  activity_type_id INT NOT NULL,
  name VARCHAR(180) NOT NULL,
  description TEXT DEFAULT NULL,
  color VARCHAR(20) DEFAULT '#3b82f6',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (activity_type_id) REFERENCES activity_types(id) ON DELETE RESTRICT,
  INDEX idx_activity_plans_user_updated (user_id, updated_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS activity_plan_segments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  plan_id INT NOT NULL,
  segment_order INT NOT NULL,
  segment_type VARCHAR(20) NOT NULL DEFAULT 'run',
  label VARCHAR(180) DEFAULT NULL,
  title VARCHAR(180) NOT NULL,
  target_type VARCHAR(20) NOT NULL DEFAULT 'distance',
  target_metric VARCHAR(20) NOT NULL DEFAULT 'none',
  target_distance_meters INT DEFAULT NULL,
  target_duration_seconds INT DEFAULT NULL,
  target_pace_min_sec_per_km DECIMAL(10,2) DEFAULT NULL,
  target_pace_max_sec_per_km DECIMAL(10,2) DEFAULT NULL,
  target_hr_min INT DEFAULT NULL,
  target_hr_max INT DEFAULT NULL,
  target_cadence_min INT DEFAULT NULL,
  target_cadence_max INT DEFAULT NULL,
  repeat_count INT NOT NULL DEFAULT 1,
  recovery_type VARCHAR(20) NOT NULL DEFAULT 'none',
  recovery_distance_meters INT DEFAULT NULL,
  recovery_duration_seconds INT DEFAULT NULL,
  group_repeat_count INT NOT NULL DEFAULT 1,
  group_recovery_type VARCHAR(20) NOT NULL DEFAULT 'none',
  group_recovery_distance_meters INT DEFAULT NULL,
  group_recovery_duration_seconds INT DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (plan_id) REFERENCES activity_plans(id) ON DELETE CASCADE,
  UNIQUE KEY uq_activity_plan_segment_order (plan_id, segment_order),
  INDEX idx_activity_plan_segments_plan (plan_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS activity_sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  scheduled_by INT DEFAULT NULL,
  plan_id INT NOT NULL,
  plan_name VARCHAR(180) NOT NULL,
  activity_type_id INT NOT NULL,
  scheduled_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'scheduled',
  notes TEXT DEFAULT NULL,
  activity_id INT DEFAULT NULL,
  started_at DATETIME DEFAULT NULL,
  completed_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (scheduled_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (plan_id) REFERENCES activity_plans(id) ON DELETE CASCADE,
  FOREIGN KEY (activity_type_id) REFERENCES activity_types(id) ON DELETE RESTRICT,
  FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE SET NULL,
  INDEX idx_activity_sessions_user_date (user_id, scheduled_date),
  INDEX idx_activity_sessions_sender (scheduled_by),
  INDEX idx_activity_sessions_status (status)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS activity_session_segments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_id INT NOT NULL,
  plan_segment_id INT DEFAULT NULL,
  segment_order INT NOT NULL,
  segment_kind VARCHAR(20) NOT NULL DEFAULT 'work',
  group_index INT DEFAULT NULL,
  group_total INT DEFAULT NULL,
  repeat_index INT DEFAULT NULL,
  repeat_total INT DEFAULT NULL,
  segment_type VARCHAR(20) NOT NULL DEFAULT 'run',
  label VARCHAR(180) DEFAULT NULL,
  title VARCHAR(180) NOT NULL,
  target_type VARCHAR(20) NOT NULL DEFAULT 'distance',
  target_metric VARCHAR(20) NOT NULL DEFAULT 'none',
  target_distance_meters INT DEFAULT NULL,
  target_duration_seconds INT DEFAULT NULL,
  target_pace_min_sec_per_km DECIMAL(10,2) DEFAULT NULL,
  target_pace_max_sec_per_km DECIMAL(10,2) DEFAULT NULL,
  target_hr_min INT DEFAULT NULL,
  target_hr_max INT DEFAULT NULL,
  target_cadence_min INT DEFAULT NULL,
  target_cadence_max INT DEFAULT NULL,
  actual_distance_meters INT DEFAULT NULL,
  actual_duration_seconds INT DEFAULT NULL,
  actual_avg_hr INT DEFAULT NULL,
  actual_avg_cadence INT DEFAULT NULL,
  is_completed TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (session_id) REFERENCES activity_sessions(id) ON DELETE CASCADE,
  FOREIGN KEY (plan_segment_id) REFERENCES activity_plan_segments(id) ON DELETE SET NULL,
  UNIQUE KEY uq_activity_session_segment_order (session_id, segment_order),
  INDEX idx_activity_session_segments_session (session_id)
) ENGINE=InnoDB;
